"""Phase 11 - Generate charts and a consolidated Markdown report.

Reads quality_indicators.csv (+ hotspots.csv) and produces PNG charts under
reports/charts/ and reports/report.md with rankings, contribution distribution,
average complexity, testability and the top hotspots.
"""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from common import CHARTS_DIR, DATA_DIR, REPORTS_DIR, get_logger  # noqa: E402

log = get_logger("report")


def _short(name: str) -> str:
    return name.split("/")[-1]


def _bar(df: pd.DataFrame, col: str, title: str, fname: str, color="#4C72B0"):
    if df.empty or col not in df.columns:
        return None
    d = df.sort_values(col, ascending=True)
    plt.figure(figsize=(9, 5))
    plt.barh([_short(r) for r in d["repository"]], d[col], color=color)
    plt.title(title)
    plt.xlabel(col)
    plt.tight_layout()
    path = CHARTS_DIR / fname
    plt.savefig(path, dpi=120)
    plt.close()
    return path


def make_charts(ind: pd.DataFrame) -> list[Path]:
    charts = []
    for col, title, fname, color in [
        ("stars", "Stars by repository", "stars.png", "#DD8452"),
        ("activity_score", "Project activity score", "activity.png", "#55A868"),
        ("avg_ccn", "Average cyclomatic complexity", "complexity.png", "#C44E52"),
        ("testability", "Testability (test methods / methods)", "testability.png", "#8172B3"),
        ("top5_commit_share_pct", "Top-5 contributor commit share (%)", "concentration.png", "#937860"),
    ]:
        p = _bar(ind, col, title, fname, color)
        if p:
            charts.append(p)
    return charts


def build_report(ind: pd.DataFrame, hotspots: pd.DataFrame, charts: list[Path]) -> str:
    lines = ["# GitHub Metrics Analyzer - Final Report", ""]
    lines.append(f"Repositories analyzed: **{len(ind)}**")
    lines.append("")

    # Ranking
    lines.append("## Repository ranking (by activity score)")
    lines.append("")
    rank_cols = ["repository", "stars", "forks", "total_commits", "contributors",
                 "avg_ccn", "testability", "activity_score"]
    rank = ind.sort_values("activity_score", ascending=False)[
        [c for c in rank_cols if c in ind.columns]]
    lines.append(rank.to_markdown(index=False))
    lines.append("")

    # Charts
    lines.append("## Charts")
    lines.append("")
    for c in charts:
        rel = c.relative_to(REPORTS_DIR).as_posix()
        lines.append(f"### {c.stem.replace('_', ' ').title()}")
        lines.append(f"![{c.stem}]({rel})")
        lines.append("")

    # Concentration risk
    lines.append("## Contribution concentration risk")
    lines.append("")
    if "concentration_risk" in ind.columns:
        conc = ind[["repository", "contributors", "top5_commit_share_pct",
                    "concentration_risk"]].sort_values(
            "top5_commit_share_pct", ascending=False)
        lines.append(conc.to_markdown(index=False))
        lines.append("")

    # Testability & maintainability
    lines.append("## Testability & maintainability")
    lines.append("")
    maint_cols = ["repository", "total_loc", "avg_ccn", "avg_method_nloc",
                  "avg_method_params", "test_methods", "testability"]
    maint = ind[[c for c in maint_cols if c in ind.columns]]
    lines.append(maint.to_markdown(index=False))
    lines.append("")

    # Modularity
    lines.append("## Modularity")
    lines.append("")
    mod_cols = ["repository", "classes", "interfaces", "methods", "inheritance_links"]
    if all(c in ind.columns for c in mod_cols):
        lines.append(ind[mod_cols].to_markdown(index=False))
        lines.append("")

    # PR health
    lines.append("## Pull request health")
    lines.append("")
    pr_cols = ["repository", "pr_open", "pr_closed", "avg_commits_per_pr",
               "avg_pr_close_hours"]
    if all(c in ind.columns for c in pr_cols):
        lines.append(ind[pr_cols].to_markdown(index=False))
        lines.append("")

    # Hotspots
    lines.append("## Top refactoring hotspots (commits x complexity)")
    lines.append("")
    if not hotspots.empty:
        top = hotspots.head(20)[["repository", "file", "commits", "avg_ccn",
                                 "hotspot_score"]]
        lines.append(top.to_markdown(index=False))
    else:
        lines.append("_No hotspot data available._")
    lines.append("")

    lines.append("---")
    lines.append("_Generated by the GitHub Metrics Analyzer pipeline._")
    return "\n".join(lines)


def main() -> None:
    ind_path = DATA_DIR / "quality_indicators.csv"
    if not ind_path.exists():
        log.error("quality_indicators.csv not found. Run compute_indicators.py.")
        return
    ind = pd.read_csv(ind_path)

    hs_path = DATA_DIR / "hotspots.csv"
    hotspots = pd.read_csv(hs_path) if hs_path.exists() else pd.DataFrame()

    charts = make_charts(ind)
    report = build_report(ind, hotspots, charts)

    out = REPORTS_DIR / "report.md"
    out.write_text(report, encoding="utf-8")
    log.info("Wrote report to %s with %d charts", out, len(charts))


if __name__ == "__main__":
    main()
